# Generated by Django 5.2.1 on 2025-05-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_client_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ("name",)},
        ),
    ]
