# Generated by Django 5.2.1 on 2025-05-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0005_clientfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientfile",
            name="file",
            field=models.FileField(upload_to="clientfiles"),
        ),
    ]
