# Generated by Django 5.2.1 on 2025-06-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0003_alter_userprofile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="active_team_id",
            new_name="active_team",
        ),
    ]
