# Generated by Django 5.2.1 on 2025-05-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0003_lead_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ("name",)},
        ),
    ]
